# Generated by Django 4.2.28 on 2026-02-24 03:48

from django.db import migrations, models


def populate_platform_role(apps, schema_editor):
    """Set platform_role for existing users based on is_superuser/is_staff flags."""
    User = apps.get_model('users', 'User')
    User.objects.filter(is_superuser=True).update(platform_role='OWNER')
    User.objects.filter(is_superuser=False, is_staff=True).update(platform_role='MAINTAINER')
    # All other users default to REPORTER (the field default)


def reverse_populate(apps, schema_editor):
    """No-op reverse — the field will be removed by reverting AddField."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='platform_role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MAINTAINER', 'Maintainer'), ('DEVELOPER', 'Developer'), ('REPORTER', 'Reporter')], default='REPORTER', max_length=20, verbose_name='Platform Role'),
        ),
        migrations.RunPython(populate_platform_role, reverse_populate),
    ]
