# Generated by Django 6.0.1 on 2026-02-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_telegramuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='feishu_avatar_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='feishu_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='feishu_union_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
