# Generated by Django 4.2.29 on 2026-03-13 01:58

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_platform_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.PlatformUserManager()),
            ],
        ),
    ]
