# Generated by Django 3.2 on 2026-01-15 11:15

from django.db import migrations

def backfill_project_members(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    ProjectMember = apps.get_model('projects', 'ProjectMember')
    
    for project in Project.objects.all():
        # Check if creator is already a member
        if not ProjectMember.objects.filter(project=project, user=project.created_by).exists():
            ProjectMember.objects.create(
                project=project, 
                user=project.created_by, 
                role='OWNER'
            )

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectmember'),
    ]

    operations = [
        migrations.RunPython(backfill_project_members),
    ]
