# Generated by Django 4.2.27 on 2026-01-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_backfill_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='extra_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Extra Configuration'),
        ),
    ]
