# Generated by Django 4.2.27 on 2026-01-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowdefinition',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Tags'),
        ),
    ]
