# Generated by Django 4.2.28 on 2026-02-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowdefinition',
            name='notify_template',
            field=models.TextField(blank=True, default='', verbose_name='通知模板'),
        ),
    ]
