# Generated by Django 4.2.29 on 2026-03-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_add_notify_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowdefinition',
            name='visible_roles',
            field=models.JSONField(blank=True, default=list, verbose_name='Visible Roles'),
        ),
        migrations.AddField(
            model_name='workflowdefinition',
            name='visible_user_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='Visible User IDs'),
        ),
    ]
