# Generated by Django 4.2.27 on 2026-01-14 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('workflows', '0002_workflowdefinition_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowdefinition',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='projects.project', verbose_name='Project'),
        ),
    ]
