# Generated by Django 4.2.28 on 2026-03-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_workflowdefinition_visible_roles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowdefinition',
            name='notify_templates',
            field=models.JSONField(blank=True, default=dict, verbose_name='通知模板配置'),
        ),
        migrations.RemoveField(
            model_name='workflowdefinition',
            name='notify_template',
        ),
    ]
