# Generated by Django 4.2.27 on 2026-01-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='model_group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='chatmessage',
            table='chat_chatmessage',
        ),
        migrations.AlterModelTable(
            name='chatsession',
            table='chat_chatsession',
        ),
    ]
