# Generated by Django 4.2.28 on 2026-03-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='source',
            field=models.CharField(choices=[('web', 'Web'), ('pipeline', 'Pipeline')], default='web', max_length=20),
        ),
    ]
