# Generated by Django 4.2.27 on 2026-02-02 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_agents', '0002_workspace_architecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenttask',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='agenttask',
            name='node_id',
        ),
        migrations.RemoveField(
            model_name='agenttask',
            name='parameters',
        ),
        migrations.RemoveField(
            model_name='agenttask',
            name='pipeline_id',
        ),
        migrations.RemoveField(
            model_name='agenttask',
            name='working_dir',
        ),
    ]
