# Generated by Django 4.2.27 on 2026-02-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_agents', '0003_remove_agenttask_environment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientagent',
            name='environment',
            field=models.JSONField(blank=True, default=dict, verbose_name='环境变量配置'),
        ),
    ]
