# Generated by Django 4.2.28 on 2026-02-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_agents', '0004_clientagent_environment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentworkspace',
            name='current_task',
        ),
        migrations.AddField(
            model_name='agenttask',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后心跳'),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='pipeline_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Pipeline ID'),
        ),
        migrations.AddField(
            model_name='agentworkspace',
            name='pipeline_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Pipeline ID'),
        ),
    ]
