"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os


def env_bool(name: str, default: bool = False) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_int(name: str, default: int) -> int:
    value = os.environ.get(name)
    if value is None:
        return default
    try:
        return int(value)
    except ValueError:
        return default


def env_list(name: str, default: list[str] | None = None) -> list[str]:
    value = os.environ.get(name)
    if value is None or not value.strip():
        return list(default or [])
    return [item.strip() for item in value.split(",") if item.strip()]

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-j%&jlm2wuetkimc$=om)rwl6)_yugnmfl9i#8he)fz&9&^t53s",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", True)

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", ["*"])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'users',
    'bamboo_engine',
    'pipeline',
    'pipeline.engine',
    'pipeline.component_framework',
    'pipeline.variable_framework',
    'pipeline.eri',
    'django_mptt_admin',
    'mptt',
    'workflows',
    'projects',
    'components',
    'tasks.apps.TasksConfig',
    'tickets',
    'django_celery_beat',
    'chat',
    'django_filters',
    'agents',
    'plugins',
    'client_agents',
    'channels',
    'config.apps.PlatformConfigApp',
]

BAMBOO_DJANGO_DATABASE_CONNECTION_NAME = 'default'

# Maximum number of times a node can be re-executed (loop limit)
# This prevents infinite loops in workflows with cyclic structures
BAMBOO_DJANGO_ERI_NODE_RERUN_LIMIT = int(os.environ.get('BAMBOO_NODE_RERUN_LIMIT', 100))

# Enable pipeline event signals for bamboo-engine hooks
ENABLE_PIPELINE_EVENT_SIGNALS = True

# Component discovery paths for bamboo-engine
# Users can customize custom component paths via CUSTOM_COMPONENT_PATHS environment variable
# Supports multiple paths separated by comma, e.g., 'plugins.components,extensions.components'
# Default: 'custom_components.components'
CUSTOM_COMPONENT_PATHS = os.environ.get('CUSTOM_COMPONENT_PATHS', 'custom_components.components')

COMPONENT_PATH = [
    'components.components',      # Built-in components
]

# Add custom component paths if configured
# Also add the root package to INSTALLED_APPS for autodiscovery to work
if CUSTOM_COMPONENT_PATHS:
    for path in CUSTOM_COMPONENT_PATHS.split(','):
        path = path.strip()
        if path:
            COMPONENT_PATH.append(path)
            # Extract the root app name (e.g., 'notion_components' from 'notion_components.components')
            app_name = path.split('.')[0]
            if app_name and app_name not in INSTALLED_APPS:
                INSTALLED_APPS.append(app_name)

# Mako template sandbox configuration for splice variables
# This allows using specific modules in splice expressions like ${my_date.strftime("%Y-%m-%d")}
MAKO_SANDBOX_IMPORT_MODULES = {
    "datetime": "datetime",  # Allow datetime module for date formatting
}

CORS_ALLOW_ALL_ORIGINS = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

# Django Channels configuration
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.environ.get('REDIS_URL', 'redis://redis:6379/3')],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'tasknexus'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'postgres'),
        'HOST': os.environ.get('DB_HOST', 'db'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        'CONN_MAX_AGE': env_int('CONN_MAX_AGE', 60),
    }
}

# Redis and Celery Configuration
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://redis:6379/1')
CELERY_ACCEPT_CONTENT = ['json', 'pickle', 'msgpack', 'yaml'] # bamboo-engine might use pickle for complex objects? "json" is usually default.
# bamboo-engine requires 'pickle'? No, it uses JSON normally but complex objects might be issue.
# Let's keep it safe. But standard is json.
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_IMPORTS = (
    'pipeline.eri.celery.tasks',
    'tasks.tasks',
)

CELERY_TIMEZONE = 'Asia/Shanghai'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# ---- Worker Memory Optimization ----
# 每个worker进程执行500个任务后自动重启，防止内存泄漏累积
CELERY_WORKER_MAX_TASKS_PER_CHILD = 500
# 降低预取数量，减少内存中缓存的任务消息
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_ACKS_LATE = env_bool('CELERY_TASK_ACKS_LATE', True)
CELERY_TASK_REJECT_ON_WORKER_LOST = env_bool('CELERY_TASK_REJECT_ON_WORKER_LOST', True)
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'visibility_timeout': env_int('CELERY_BROKER_VISIBILITY_TIMEOUT', 3600),
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ.get('REDIS_URL', 'redis://redis:6379/2'),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.environ.get('TIME_ZONE', 'Asia/Shanghai')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}
