# Generated by Django 4.2.27 on 2026-01-14 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflows', '0003_workflowdefinition_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pipeline_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('FINISHED', 'Finished'), ('FAILED', 'Failed'), ('REVOKED', 'Revoked')], default='CREATED', max_length=32)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('execution_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='workflows.workflowdefinition')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
