# Generated by Django 4.2.28 on 2026-02-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='notify_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='notify_user_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
