# Generated by Django 4.2.28 on 2026-02-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskinstance_notify_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='feishu_notify_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='feishu_notify_open_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
