# Generated by Django 4.2.27 on 2026-01-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_scheduledtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodictask',
            name='context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='context',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
