# Generated by Django 4.2.28 on 2026-02-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_add_feishu_notify_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodictask',
            name='feishu_notify_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='periodictask',
            name='feishu_notify_open_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='periodictask',
            name='notify_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='periodictask',
            name='notify_user_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='feishu_notify_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='feishu_notify_open_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='notify_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='notify_user_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='webhooktask',
            name='feishu_notify_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webhooktask',
            name='feishu_notify_open_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='webhooktask',
            name='notify_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webhooktask',
            name='notify_user_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
