# Generated by Django 4.2.29 on 2026-03-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_periodictask_feishu_notify_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeishuApprovalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('content', models.TextField()),
                ('reviewer_open_ids', models.JSONField(default=list)),
                ('decisions', models.JSONField(default=dict)),
                ('message_ids', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
