# Generated by Django 4.2.29 on 2026-03-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_feishu_approval_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='feishuapprovalrecord',
            name='callback_node_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='feishuapprovalrecord',
            name='callback_node_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
