# Generated by Django 4.2.27 on 2026-01-21 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_chatsession_last_summarized_message_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
    ]
