# Generated by Django 4.2.29 on 2026-03-05 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_feishuapprovalrecord_callback_node_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeishuApprovalRecord',
        ),
    ]
