# Generated by Django 4.2.27 on 2026-01-30 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflows', '0003_workflowdefinition_project'),
        ('tasks', '0008_remove_data_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('secret', models.CharField(blank=True, max_length=128, null=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('total_run_count', models.IntegerField(default=0)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.workflowdefinition')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
