# Generated by Django 4.2.27 on 2026-02-04 09:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_workflowdefinition_project'),
        ('tasks', '0009_webhook_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeExecutionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(db_index=True, max_length=64)),
                ('duration', models.IntegerField()),
                ('pipeline_id', models.CharField(db_index=True, max_length=64)),
                ('finished_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_cords', to='workflows.workflowdefinition')),
            ],
            options={
                'ordering': ['-finished_at'],
                'indexes': [models.Index(fields=['workflow', 'node_id'], name='tasks_nodee_workflo_4efdbd_idx')],
            },
        ),
    ]
