# Generated by Django 4.2.28 on 2026-02-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('icon', models.CharField(default='Box', max_length=100, verbose_name='Icon Name')),
            ],
            options={
                'verbose_name': 'Component Category',
                'verbose_name_plural': 'Component Categories',
            },
        ),
    ]
