# Generated by Django 4.2.28 on 2026-03-12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("components", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentNodeTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, verbose_name="Template Name")),
                ("node_data", models.JSONField(default=dict, verbose_name="Node Data")),
                ("component_code", models.CharField(max_length=128, verbose_name="Component Code")),
                (
                    "component_version",
                    models.CharField(blank=True, default="", max_length=64, verbose_name="Component Version"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_node_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Component Node Template",
                "verbose_name_plural": "Component Node Templates",
                "ordering": ["-updated_at"],
            },
        ),
    ]
