# Generated by Django 4.2.29 on 2026-03-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_componentnodetemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentnodetemplate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
