# Generated by Django 4.2.29 on 2026-03-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('PENDING_RELEASE', 'Pending Release'), ('DONE', 'Done')], default='TODO', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketstatuslog',
            name='from_status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('PENDING_RELEASE', 'Pending Release'), ('DONE', 'Done')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketstatuslog',
            name='to_status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('PENDING_RELEASE', 'Pending Release'), ('DONE', 'Done')], max_length=20),
        ),
    ]
